env:
  env_config:
    num_order: 200
    num_service: 100
    width: 20
    height: 20
    num_organization: 2
    episode_length: 10
    ratio_medium: 0
  env_name: CloudManufacturing

trainer:
  num_workers: 1
  batch_mode: truncate_episodes
  no_done_at_end: false
  observation_filter: NoFilter
  rollout_fragment_length: 20
  microbatch_size: 20
  train_batch_size: 80

general:
  ckpt_frequency_steps: 10000
  episodes: 100

agent_policy:
  clip_param: 0.3
  entropy_coeff: 0.025
  entropy_coeff_schedule: null
  gamma: 0.998
  grad_clip: 10.0
  kl_coeff: 0.0
  kl_target: 0.01
  lambda: 0.98
  lr: 0.0003
  lr_schedule: null
  model:
    custom_model: AgentPolicy
    custom_options:
      fc1_dim: 24
      fc2_dim: 64
  use_gae: true
  vf_clip_param: 50.0
  vf_loss_coeff: 0.05
  vf_share_layers: false

